---
title: 'Final Assignment: solutions'
author: "Henrique Sposito & Livio Silva-Muller"
date: "October 2022"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
library(ggplot2)
library(dplyr)
library (tidyr)
library(readr)
library(readxl)
library(ggplot2)
options(scipen=999) # removes scientific notation


setwd("~/Documents/GitHub/Fundamentals_of_R_IHEID2022/Final Assignment")
co2 <- read_excel("co2_emissions.xlsx")
country_region <- read_csv("country_region.csv")
pop_dat <- readRDS("pop_dat.rds")
gdp <- readRDS("gdp.rds")

```

```{r untidying pop, eval=FALSE, include=FALSE}
pop <- read_excel("~/Downloads/API_SP.POP.TOTL_DS2_en_excel_v2_4666579.xls")

urban_pop <- read_excel("~/Downloads/API_SP.URB.TOTL.IN.ZS_DS2_en_excel_v2_4663801.xls")


names(pop) <- pop[3,] # making fourth line names.
pop <- pop[-c(1:3), ] #

names(urban_pop) <- urban_pop[3,] # making fourth line names.
urban_pop <- urban_pop[-c(1:3), ] #


pop <-  pivot_longer(pop, 5:66, names_to="year", values_to= "total_pop") %>% select(c(1,2,5,6)) %>% filter(year > 1989)

urban_pop <-  pivot_longer(urban_pop, 5:66, names_to="year", values_to= "urban_pop_share") %>% select(c(1,2,5,6)) %>% filter(year > 1989)

total_pop <- pop %>% left_join(urban_pop) %>% pivot_longer(4:5)

saveRDS(total_pop, file="pop_dat.rds")

```

```{r untidying gdp, eval=FALSE, include=FALSE}

current_gdp <- read_excel("current_gdp.xls")

current_gdp <-  pivot_longer(current_gdp, 5:66, names_to="year", values_to= "gdp") %>% select(c(1,2,5,6)) %>% filter(year > 1989) %>% drop_na(gdp)

current_gdp <- unite(current_gdp,"country_name;country_code;year;gdp", sep=";")

saveRDS(current_gdp, file="gdp.rds")

```

##Question 1
```{r}
names(co2) <- co2[4,] # making fourth line names.
co2 <- co2[-c(1:4), ] # removing lines that are not observations.

co2 <- co2 %>% 
  pivot_longer(5:66, names_to="year", values_to= "co2_emissions") %>% 
  left_join(country_region)%>%
  drop_na(co2_emissions)%>%
  rename(country_name=`Country Name`, country_code= `Country Code`, income_group= `IncomeGroup`, region=Region)%>%
  select(-c(`Indicator Name`, `Indicator Code`,TableName))%>%
  drop_na(region) #tidy, with regions and income groups.

pop_dat <- pop_dat %>% pivot_wider(names_from ="name", values_from="value") %>% rename(country_name=`Country Name`, country_code= `Country Code`)

gdp <- gdp %>% separate(1, sep=";", into=c("country_name", "country_code", "year", "gdp")) #tidy

co2_dat <- co2 %>% left_join(pop_dat) %>% left_join(gdp) #one single dataset
```

##Question 2
```{r}
co2_dat$income_group <- ifelse(co2_dat$country_code=="VEN", "Upper middle income", co2_dat$income_group)

co2_dat <- co2_dat %>% drop_na()
```

##Question 3
```{r}
co2_dat$total_pop <- as.numeric(co2_dat$total_pop)
co2_dat$gdp <- as.numeric(co2_dat$gdp)
co2_dat$urban_pop_share <- as.numeric(co2_dat$urban_pop_share)
co2_dat$year <- as.numeric(co2_dat$year)

unique(co2_dat$country_name)
dim(co2_dat)

```

##Question 4
```{r}
co2_dat <- co2_dat %>%
  mutate(co2_per_cap=co2_emissions/total_pop,
         gdp_per_cap=gdp/total_pop)
```

##Question 5
```{r 5a}
co2_dat %>%
  group_by(country_name) %>%
  summarise(total_emission =sum(co2_emissions))%>%
  arrange(-total_emission)%>%
  slice_head(n=20)
```

```{r 5b}
co2_dat %>% 
  group_by(country_name) %>%
  summarise(emi=mean(co2_per_cap)) %>%
  arrange(-emi)
```

```{r 5c}
decades_rank <- co2_dat %>%
  mutate(decades=case_when(
    year<2000 ~ "1990s",
    year<2011 ~ "2000s",
    year<2020 ~ "2010s"
  )) %>%
  group_by(country_name, decades)%>%
  summarise(emi=mean(co2_per_cap)) %>%
  pivot_wider(names_from=decades, values_from=emi)
```

##Question 6

```{r 6a}
co2_dat %>%
  group_by(year)%>%
  summarise(total =mean(co2_per_cap)) %>%
  ggplot(aes(x=year, y=total))+
  geom_line()
```

```{r 6b}
co2_dat %>%
  filter(country_name=="United States" |country_name=="China" | country_name=="India" ) %>%
  group_by(year, country_name)%>%
  summarise(total =mean(co2_per_cap)) %>%
  ggplot(aes(x=year, y=total, color=country_name))+
  geom_line()
```

```{r 6c}
co2_dat %>%
  group_by(year, income_group)%>%
  summarise(total =mean(co2_per_cap)) %>%
  drop_na() %>%
  ggplot(aes(x=year, y=total, color=income_group))+
  geom_line()
```

##Question 7

```{r 7a}
co2_dat %>%
  drop_na()%>%
  ggplot(aes(y=co2_emissions, x=total_pop))+
  geom_point(color="gold", alpha=0.5)+
  geom_smooth(se=FALSE, color="black", size=.75)+
  scale_x_log10()+
  scale_y_log10()+
  facet_wrap(~income_group)
```

```{r 7b}
co2_dat %>% 
  ggplot(aes(y=co2_per_cap, x=income_group))+
  geom_boxplot()+
  scale_y_log10()
```

##Question 8

```{r 8a}
co2_dat %>%
    group_by(country_name)%>%
    ggplot(aes(x=co2_emissions, y=urban_pop_share))+
    geom_point(position="jitter", color="#ec2d01", alpha=.5)+
    geom_smooth(se=FALSE, size=.75, color="black", method="lm")+
    scale_x_log10()
```

```{r 8b income_group}
co2_dat %>%
    ggplot(aes(x=co2_emissions, y=urban_pop_share))+
    geom_point(position="jitter", color="#ec2d01", alpha=.5)+
    geom_smooth(se=FALSE, size=.75, color="black", method="lm")+
    scale_x_log10()+
    facet_wrap(~income_group)
```

```{r 8c region}
co2_dat %>%
    ggplot(aes(x=co2_emissions, y=urban_pop_share))+
    geom_point(position="jitter", color="#ec2d01", alpha=.5)+
    geom_smooth(se=FALSE, size=.75, color="black", method="lm")+
    scale_x_log10()+
    facet_wrap(~region)
```

##Question 9

```{r geom_col, eval=FALSE}

flag_per_capita <- co2_dat %>%
  group_by(country_name)%>%
  summarise(co2_per_cap_2= mean(co2_per_cap))%>%
  arrange(-co2_per_cap_2)%>%
  slice_head(n=20)%>%
  mutate(top_emitter= "top 20 emitter per capita")
  

co2_dat %>% 
  left_join(flag_per_capita)%>%
  mutate(top_emitter=replace_na(top_emitter, "rest"))+
  group_by(country_name, top_emitter)%>%
  summarise(tot_co2=sum(co2_emissions))%>%
  ungroup()%>%
  arrange(-tot_co2)%>%
  slice_head(n=50)%>%
  ggplot(aes(x=reorder(country_name, tot_co2), y=tot_co2, fill=top_emitter))+
  geom_col()+
  coord_flip()
  
```
