---
title: 'Plotting Data'
subtitle: 'Fundamentals of R - Homework'
date: "October 2022"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---

- All materials for the exercises below are available in the homework folder.
- Please submit a PDF document generated from your R Markdown file containing your codes and plots.

# Income of International Organizations

The 'io_income_rs.csv' dataset contains funding data from some international organizations in Geneva.

Please load the dataset, we will be working with it today.

*Tip: Adding titles, legends, and themes to your plots helps us help you!*

## Question 1

Create a bar plot displaying the top 10 overall donors and their total donations to all international organizations. Please color the donors by their type (i.e. public or private).

## Question 2

Has the amount the US donates to all issue areas increased over time? Please illustrate this relationship in a line plot, colored by the respective issue areas.

## Question 3

Plot the distribution of all donations in the year 2000 and in the year 2020 comparing public and private donors. Are there outliers for either of these types of donors in 2000? What about in 2020? (Tip: box plots are great for distributions! Please treat year as factor and scale the nominal amount using "scale_y_log10(labels = scales::dollar)").

## Question 4

Create four scatter plots, one for each issue area, containing all donation by year per donor type (Tip: use "facet_wrap(~issue_area)"). The shape of the points should reflect the donor type (Tip: use "geom_point(aes(shape = donor_type"))"). In each facet, please add a smoothed line to show the direction of the relationship (TIP: use "geom_smooth()"). The smoothed lines should be colored "red".
